### ISSUE TITLE
Can not start anthracite

### ISSUE THREAD

**Issue by nindza** [Dieterbe/anthracite#27]
When I try to start antracite it failes with:

Traceback (most recent call last):
  File "./anthracite-web.py", line 437, in <module>
    backend = Backend(config)
  File "/opt/prometheus/anthracite/anthracite/backend.py", line 135, in __init__
    "index": "not_analyzed"
  File "/opt/prometheus/anthracite/anthracite/rawes/rawes/elastic.py", line 53, in post
    return self.request('post', path, **kwargs)
  File "/opt/prometheus/anthracite/anthracite/rawes/rawes/elastic.py", line 75, in request
    return self.connection.request(method, new_path, **kwargs)
  File "/opt/prometheus/anthracite/anthracite/rawes/rawes/http_connection.py", line 43, in request
    return self._decode(response)
  File "/opt/prometheus/anthracite/anthracite/rawes/rawes/http_connection.py", line 49, in _decode
    decoded = json.loads(response.text)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I tried this on Ubuntu 14.04.5, and latest Elasticsearch 5.2.1. Could it be that I should try with some older version of Elasticsearch?

**Comment by kishoreyellamraju** [comment]
@nindza ES 5.x has lot of breaking changes. I highly doubt this code work with newer version of ES. I use it with ES 2.x and it works great.
